import { audioLicenseFor, BibleLicenseKind } from "@/lib/bibleLicense";
import type { Bible } from "@/app/common/bible/model/Bible";

/**
 * Licence metadata attached to every Content API response.
 *
 * The marketing pipeline PUBLISHES what it reads — into videos, captions and
 * thumbnails — which is a materially different act from rendering it in a
 * reader. Whether a given translation may be republished, and whether a dataset
 * demands attribution, is therefore not a detail the consumer should have to
 * look up. It travels with the payload.
 *
 * `audioLicensed` reuses the audit in src/lib/bibleLicense.ts verbatim rather
 * than restating it: that file is the single source of truth for which
 * translations are public-domain or openly licensed, and it defaults to false
 * for anything unrecognised.
 */

export type TranslationLicense = {
	/** Cleared for republishing text and audio: public-domain or open-licensed. */
	openLicensed: boolean;
	kind: BibleLicenseKind | "unverified";
	label: string | null;
	/** Where the verse text itself came from. */
	textSource: "api.bible";
	attribution: string;
	/** Plain-language rule for a publishing consumer. */
	publishing: string;
};

const OPEN_PUBLISHING =
	"Cleared for republishing, including in video. Credit the translation by name.";

const RESTRICTED_PUBLISHING =
	"NOT cleared for republishing. This translation is not on the open-licence allowlist " +
	"in src/lib/bibleLicense.ts — do not quote its text in published material or narrate it. " +
	"Use an open-licensed translation instead (see /api/content/v1/meta).";

export function translationLicense(bible: Pick<Bible, "version" | "name">): TranslationLicense {
	const licensed = audioLicenseFor(bible);
	return {
		openLicensed: licensed !== null,
		kind: licensed?.kind ?? "unverified",
		label: licensed?.label ?? null,
		textSource: "api.bible",
		attribution: `${bible.name} — text via API.Bible (api.bible).`,
		publishing: licensed ? OPEN_PUBLISHING : RESTRICTED_PUBLISHING,
	};
}

/**
 * Character data is CC-BY-SA 4.0, which is share-alike: a published derivative
 * must credit the dataset. Stated on every character response so a generated
 * caption can carry the credit without anyone remembering to add it.
 */
export const CHARACTER_DATA_LICENSE = {
	source: "theographic-bible-metadata",
	url: "https://github.com/robertrouse/theographic-bible-metadata",
	license: "CC-BY-SA 4.0",
	attribution: "Character data from theographic-bible-metadata (CC-BY-SA 4.0).",
	publishing:
		"Share-alike: published material derived from this data must credit the dataset and its licence. " +
		"Narrative sections (overview, significance, timeline) are generated by this product, " +
		"with every scripture citation checked against the character's real verse mentions.",
} as const;
